obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
obj-$(CONFIG_OPPO_DEBUG_ASSERT)	+=  oppo_trace/
#obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/

#ifdef VENDOR_EDIT
#obj-y     +=  oppo_hypnus/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)	+=  oppo_shutdown_detect/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
obj-y +=  oppo_criticallog/
#endif /* VENDOR_EDIT */

obj-$(CONFIG_OPPO_SVELTE)     +=  oppo_svelte/
